apiVersion: demo.iohkdev.io/v1alpha1
kind: Application
metadata:
  name: hello
spec:
  image:
    repository: nginxdemos/hello
    tag: "latest"
  service:
    ports:
      - name: http
        port: 80
        protocol: TCP
  gateway:
    hosts:
      - host: helloworld.test.aws.iohkdev.io
        paths:
          - path: /
            pathType: PathPrefix
  cardanoNode:
    network: mainnet
    configCloner: true
